### AUTOCOMPLETION
#autoload -Uz compinit && compinit
autoload -U +X compinit && compinit
setopt COMPLETE_ALIASES

# globbing case-insensitive
setopt GLOB_COMPLETE

# autocompletion case-sensitive
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 

# auto-complation definitions from bash
autoload -U +X bashcompinit && bashcompinit
[[ -r ~/Projects/autopkg_complete/autopkg ]] && source ~/Projects/autopkg_complete/autopkg 

# correct paths
setopt CORRECT_ALL


### ALIASES 

# source profile
source ~/.profile

# kubectl
[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)


### VISUALS 

# init prompt 
autoload -Uz promptinit
promptinit

#preview prompts
#prompt -p
#prompt elite2 red 
PROMPT=' %(?.%F{green}👍.%F{red}💩%?)%f %B%F{241}%2~%f%b %F{blue}%#%f ' 
RPROMPT='%F{241}%*%f'

# ensure correct colors
[[ "$COLORTERM" == (24bit|truecolor) || "${terminfo[colors]}" -eq '16777216' ]] || zmodload zsh/nearcolor


### VIMIFY THE WHOLE THING MODE
source $HOME/.zsh-vim-mode/zsh-vim-mode.plugin.zsh

### EOF
