### AUTOCOMPLETION
autoload -Uz compinit 
compinit
setopt COMPLETE_ALIASES


### ALIASES 

# source profile
source ~/.profile

# kubectl
[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)


### VISUALS 

# init prompt 
autoload -Uz promptinit
promptinit

#preview prompts
#prompt -p
#prompt elite2 red 
PROMPT='[%F{red}%y%f] %F{red}%n%f@%F{white}%m%f %F{blue}%B%~%b%f %# '
RPROMPT='[%F{red}%?%f %F{white}%*%f]'

# ensure correct colors
[[ "$COLORTERM" == (24bit|truecolor) || "${terminfo[colors]}" -eq '16777216' ]] || zmodload zsh/nearcolor


### VIMIFY THE WHOLE THING MODE
source $HOME/.zsh-vim-mode/zsh-vim-mode.plugin.zsh

### EOF
